### ISSUE TITLE
[Question] 'NoneType' object has no attribute 'fill' ; when trying to render

### ISSUE THREAD

**Issue by nandu-k01** [Farama-Foundation/PettingZoo#1131]
### Question

```
/home/zorx/miniforge3/envs/py8/bin/python /home/zorx/Documents/Multi_Agent/maddpg-pettingzoo-pytorch/evaluate.py
episode 1, adversary_0: 30.000000; adversary_1: 30.000000; adversary_2: 30.000000; agent_0: -45.421943; 
Traceback (most recent call last):
  File "/home/zorx/Documents/Multi_Agent/maddpg-pettingzoo-pytorch/evaluate.py", line 120, in <module>
    next_states, rewards, dones, infos, _ = env.step(actions)
  File "/home/zorx/miniforge3/envs/py8/lib/python3.8/site-packages/pettingzoo/utils/conversions.py", line 207, in step
    self.aec_env.step(actions[agent])
  File "/home/zorx/miniforge3/envs/py8/lib/python3.8/site-packages/pettingzoo/utils/wrappers/order_enforcing.py", line 91, in step
    super().step(action)
  File "/home/zorx/miniforge3/envs/py8/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py", line 116, in step
    self.env.step(action)
  File "/home/zorx/miniforge3/envs/py8/lib/python3.8/site-packages/pettingzoo/utils/wrappers/assert_out_of_bounds.py", line 26, in step
    super().step(action)
  File "/home/zorx/miniforge3/envs/py8/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py", line 116, in step
    self.env.step(action)
  File "/home/zorx/miniforge3/envs/py8/lib/python3.8/site-packages/pettingzoo/mpe/_mpe_utils/simple_env.py", line 263, in step
    self.render()
  File "/home/zorx/miniforge3/envs/py8/lib/python3.8/site-packages/pettingzoo/mpe/_mpe_utils/simple_env.py", line 279, in render
    self.draw()
  File "/home/zorx/miniforge3/envs/py8/lib/python3.8/site-packages/pettingzoo/mpe/_mpe_utils/simple_env.py", line 289, in draw
    self.screen.fill((255, 255, 255))
AttributeError: 'NoneType' object has no attribute 'fill'
(py8) zorx@zorx:~/Documents/Multi_Agent/maddpg-pettingzoo-pytorch$ /home/zorx/miniforge3/envs/py8/bin/python /home/zorx/Documents/Multi_Agent/maddpg-pettingzoo-pytorch/evaluate.py
episode 1, adversary_0: 60.000000; adversary_1: 60.000000; adversary_2: 60.000000; agent_0: -67.199279; 
Traceback (most recent call last):
  File "/home/zorx/Documents/Multi_Agent/maddpg-pettingzoo-pytorch/evaluate.py", line 120, in <module>
    next_states, rewards, dones, infos, _ = env.step(actions)
  File "/home/zorx/miniforge3/envs/py8/lib/python3.8/site-packages/pettingzoo/utils/conversions.py", line 207, in step
    self.aec_env.step(actions[agent])
  File "/home/zorx/miniforge3/envs/py8/lib/python3.8/site-packages/pettingzoo/utils/wrappers/order_enforcing.py", line 91, in step
    super().step(action)
  File "/home/zorx/miniforge3/envs/py8/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py", line 116, in step
    self.env.step(action)
  File "/home/zorx/miniforge3/envs/py8/lib/python3.8/site-packages/pettingzoo/utils/wrappers/assert_out_of_bounds.py", line 26, in step
    super().step(action)
  File "/home/zorx/miniforge3/envs/py8/lib/python3.8/site-packages/pettingzoo/utils/wrappers/base.py", line 116, in step
    self.env.step(action)
  File "/home/zorx/miniforge3/envs/py8/lib/python3.8/site-packages/pettingzoo/mpe/_mpe_utils/simple_env.py", line 263, in step
    self.render()
  File "/home/zorx/miniforge3/envs/py8/lib/python3.8/site-packages/pettingzoo/mpe/_mpe_utils/simple_env.py", line 279, in render
    self.draw()
  File "/home/zorx/miniforge3/envs/py8/lib/python3.8/site-packages/pettingzoo/mpe/_mpe_utils/simple_env.py", line 289, in draw
    self.screen.fill((255, 255, 255))
AttributeError: 'NoneType' object has no attribute 'fill'
```

when rendering after training getting this error.

**Comment by elliottower** [comment]
Can you give a full reproduction script? And which version are you using? Because on the master branch we just fixed another MPE render error, if you haven’t you should try cloning the repo and install locally with pip install -e .

**Comment by elliottower** [comment]
My guess is it has to do with terminations and truncations though, your code sets step equal to obs, rew, done, info, _ but that’s incorrect, done does not exist and hasn’t for a while, it’s observation, reward, termination, truncation, info 

So it may be that your env has truncated (time limit) but your script does not register this. Though I believe it would say “when agent is dead the only valid action is None” in that case, but it would probably explain the screen being None. Anyways hard to judge without a script to look at.

**Comment by nandu-k01** [comment]
Thanks for helping out, This is the evaluation script I'm using ,
'''     env_name = simple_tag_v3
    folder = 2
    episode_num = 100
    episode_length = 50


    model_dir = os.path.join('./results', str(env_name), str(folder))
    assert os.path.exists(model_dir)
    gif_dir = os.path.join(model_dir, 'gif')
    if not os.path.exists(gif_dir):
        os.makedirs(gif_dir)
    gif_num = len([file for file in os.listdir(gif_dir)])  # current number of gif

    env, dim_info = get_env(env_name, episode_length)
    maddpg = MADDPG.load(dim_info, os.path.join(model_dir, 'model.pt'))

    agent_num = env.num_agents
    # reward of each episode of each agent
    episode_rewards = {agent: np.zeros(episode_num) for agent in env.agents}
    for episode in range(episode_num):
        states = env.reset()[0]
        agent_reward = {agent: 0 for agent in env.agents}  # agent reward of the current episode
        frame_list = []  # used to save gif
        while env.agents:  # interact with the env for an episode
            actions = maddpg.select_action(states)
            next_states, rewards, dones, infos, _ = env.step(actions)
            # frame_list.append(Image.fromarray(env.render(mode='rgb_array')))
            states = next_states

            for agent_id, reward in rewards.items():  # update reward
                agent_reward[agent_id] += reward

        env.close()
        message = f'episode {episode + 1}, '
        # episode finishes, record reward
        for agent_id, reward in agent_reward.items():
            episode_rewards[agent_id][episode] = reward
            message += f'{agent_id}: {reward:>4f}; '
        print(message)
        # # save gif
        # frame_list[0].save(os.path.join(gif_dir, f'out{gif_num + episode + 1}.gif'),
        #                    save_all=True, append_images=frame_list[1:], duration=1, loop=0)

    # training finishes, plot reward
    fig, ax = plt.subplots()
    x = range(1, episode_num + 1)
    for agent_id, rewards in episode_rewards.items():
        ax.plot(x, rewards, label=agent_id)
    ax.legend()
    ax.set_xlabel('episode')
    ax.set_ylabel('reward')
    total_files = len([file for file in os.listdir(model_dir)])
    title = f'evaluate result of maddpg solve {env_name} {total_files - 3}'
    ax.set_title(title)
'''

**Comment by nandu-k01** [comment]
Hey,
Thanks for pointing out the issue, it was an issue with truncation, fixed it.

**Comment by elliottower** [comment]
Glad to hear, cheers
