### ISSUE TITLE
[Bug Report] broken tests for connect_four in CI 

### ISSUE THREAD

**Issue by David-GERARD** [Farama-Foundation/PettingZoo#1242]
### Describe the bug

The following tests are failing in CI for any PR:
- `Tutorial tests / tutorial-test (3.8, SB3/connect_four)`
- `Tutorial tests / tutorial-test (3.9, SB3/connect_four)`
-  `Tutorial tests / tutorial-test (3.10, SB3/connect_four)`
- `Tutorial tests / tutorial-test (3.11, SB3/connect_four)`

### Code example

Error message:

```bash
Installed /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/AutoROM/roms/zaxxon.bin
Done!
Starting training on connect_four_v3.
Traceback (most recent call last):
  File "/Users/davidgerard/Desktop/Farama/PettingZoo/tutorials/SB3/connect_four/sb3_connect_four_action_mask.py", line 188, in <module>
    train_action_mask(env_fn, steps=20_480, seed=0, **env_kwargs)
  File "/Users/davidgerard/Desktop/Farama/PettingZoo/tutorials/SB3/connect_four/sb3_connect_four_action_mask.py", line 86, in train_action_mask
    env = ActionMasker(env, mask_fn)  # Wrap to enable masking (SB3 function)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sb3_contrib/common/wrappers/action_masker.py", line 20, in __init__
    super().__init__(env)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gymnasium/core.py", line 278, in __init__
    assert isinstance(env, Env)
           ^^^^^^^^^^^^^^^^^^^^
AssertionError
```
### Additional context:

- The env being examined has the following wrapper structure: `<SB3ActionMaskWrapper<connect_four_v3>>`.
- `connect_four_v3` is inherited from `pettingzoo.AECEnv`.
- `SB3ActionMaskWrapper` is inherited from `pettingzoo.utils.BaseWrapper` itself inherited from `pettingzoo.AECEnv`.

**Comment by David-GERARD** [comment]
### Update: 

- The bug has been identified as having appeared with `gymnasium v1.0.0a1`,  with no error encountered when using `gymnasium v0.29.1`.
- As pointed out by @pseudo-rnd-thoughts, the following warning indicates that the error likely comes from the deprecation of the method `Wrapper.__get_attr__` in favour of the new `Wrapper.get_wrapper_attr` as per Farama-Foundation/Gymnasium#535 
- It is still unclear to me why this change created the bug, but I am looking into it.
