### ISSUE TITLE
Manual control bug

### ISSUE THREAD

**Issue by jkterry1** [Farama-Foundation/PettingZoo#499]
from pettingzoo.butterfly import pistonball_v4
pistonball_v4.manual_control(ball_mass=.0001, ball_elasticity=50000)

Gives the error

```
Traceback (most recent call last):
  File "/Users/justinterry/Documents/random_demo.py", line 2, in <module>
    pistonball_v4.manual_control(ball_mass=.0001, ball_elasticity=50000)
  File "/usr/local/lib/python3.9/site-packages/pettingzoo/butterfly/pistonball/manual_control.py", line 53, in manual_control
    env.step(a)
  File "/usr/local/lib/python3.9/site-packages/pettingzoo/utils/wrappers/order_enforcing.py", line 68, in step
    super().step(action)
  File "/usr/local/lib/python3.9/site-packages/pettingzoo/utils/wrappers/base.py", line 68, in step
    self.env.step(action)
  File "/usr/local/lib/python3.9/site-packages/pettingzoo/utils/wrappers/clip_out_of_bounds.py", line 24, in step
    assert (
AssertionError: action should have shape (1,), has shape ()
```

**Comment by rlew631** [comment]
Just tried recreating the error running PettingZoo 1.14.0 and got a deprecation error. Running _from pettingzoo.butterfly import pistonball_v5_ results in an import error.

I saw there was a __master_v1.11.2__ branch on the repo. Should I roll back to that and attempt to debug or focus on fixing the import on the current release and go from there?

**Comment by jkterry1** [comment]
Hey,

v5 should work if you're using the newest version on pypi, I think master might be on v6 now. What import error are you getting?

**Comment by rlew631** [comment]
So this is weird... I was getting
`Traceback (most recent call last):
  File "/Users/rlew/Documents/pettingzoo/demo.py", line 1, in <module>
    from pettingzoo.butterfly import pistonball_v5
  File "/usr/local/lib/python3.9/site-packages/pettingzoo/butterfly/__init__.py", line 5, in __getattr__
    return depricated_handler(env_name, __path__, __name__)
  File "/usr/local/lib/python3.9/site-packages/pettingzoo/utils/deprecated_module.py", line 42, in depricated_handler
    raise ImportError(f"cannot import name '{env_name}' from '{module_name}'")
ImportError: cannot import name 'pistonball_v5' from 'pettingzoo.butterfly'`
when trying to run a clean install of PettingZoo.

Changing my code to:
`from pettingzoo.butterfly.pistonball import pistonball
pistonball.manual_control(ball_mass=.0001, ball_elasticity=50000)`
gave me a `module not found` error for pygame and pymunk. After updating pip and pip installing both of those libraries I was able to recreate the original error you got by running
`from pettingzoo.butterfly import pistonball_v5
pistonball_v5.manual_control(ball_mass=.0001, ball_elasticity=50000)`
or
`from pettingzoo.butterfly.pistonball import pistonball
pistonball.manual_control(ball_mass=.0001, ball_elasticity=50000)`

I'm guessing it was just a pip error but it's hard to tell since I installed the packages at the same time

**Comment by rlew631** [comment]
Anyways, time to get into the real debugging now

**Comment by benblack769** [comment]
This import error is definitely a serious ghost.
