### ISSUE TITLE
[Bug] RLlib examples & supersuit imports broken since new pettingzoo release.

### ISSUE THREAD

**Issue by sven1977** [Farama-Foundation/PettingZoo#502]
We are seeing the following error trace since the new release in our RLlib CI tests (those that have `import [supersuit|pettingzoo]` in them):

```
Traceback (most recent call last):
--
  | File "/root/.cache/bazel/_bazel_root/5fe90af4e7d1ed9fcf52f59e39e126f5/execroot/com_github_ray_project_ray/bazel-out/k8-opt/bin/rllib/examples/pettingzoo_env.runfiles/com_github_ray_project_ray/rllib/examples/pettingzoo_env.py", line 4, in <module>
  | from supersuit import normalize_obs_v0, dtype_v0, color_reduction_v0
  | File "/opt/miniconda/lib/python3.6/site-packages/supersuit/__init__.py", line 1, in <module>
  | from .generic_wrappers import * # NOQA
  | File "/opt/miniconda/lib/python3.6/site-packages/supersuit/generic_wrappers/__init__.py", line 1, in <module>
  | from .frame_skip import frame_skip_v0 # NOQA
  | File "/opt/miniconda/lib/python3.6/site-packages/supersuit/generic_wrappers/frame_skip.py", line 3, in <module>
  | from pettingzoo.utils.wrappers import BaseWrapper, BaseParallelWraper
  | ImportError: cannot import name 'BaseParallelWraper'
```

OS: Linux
py: 3.6
pettingzoo 1.11.0
supersuit 3.2.0

@jkterry1

**Comment by jkterry1** [comment]
@sven1977 We should have a PR updating RLlib's Pettingzoo support in the near future

**Comment by jkterry1** [comment]
Closing in favor of the PR up on RLlib that needs to be merged
