### ISSUE TITLE
Tutorial error: `frame_stack_v1` cause error

### ISSUE THREAD

**Issue by dat-boris** [Farama-Foundation/PettingZoo#512]
Hi there,

Thanks so much for the project!  I'm getting started and trying out 13 lines tutorial:

https://towardsdatascience.com/multi-agent-deep-reinforcement-learning-in-15-lines-of-code-using-pettingzoo-e0b963c0820b

```
env = pistonball_v4.parallel_env(
    n_pistons=20,
    # Thanks for the recent fix!
    #local_ratio=0,
    time_penalty=-0.1, continuous=True,
    random_drop=True, random_rotate=True, ball_mass=0.75, ball_friction=0.3,
    ball_elasticity=1.5, max_cycles=125
)
env = ss.color_reduction_v0(env, mode='B')
env = ss.resize_v0(env, x_size=84, y_size=84)
env = ss.frame_stack_v1(env, 3)
env = ss.pettingzoo_env_to_vec_env_v0(env)
# error thrown here
env = ss.concat_vec_envs_v0(env, 8, num_cpus=1, base_class='stable_baselines3')
```

And I'm encountering the following error:
```
Traceback (most recent call last):
  File "/<project root>/13_lines.py", line 16, in <module>
    env = ss.frame_stack_v1(env, 3)
  File "/<project venv>/lib/python3.9/site-packages/stable_baselines3/ppo/ppo.py", line 301, in learn
    return super(PPO, self).learn(
  File "/<project venv>/lib/python3.9/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 229, in learn
    total_timesteps, callback = self._setup_learn(
  File "/<project venv>/lib/python3.9/site-packages/stable_baselines3/common/base_class.py", line 421, in _setup_learn
    self._last_obs = self.env.reset()  # pytype: disable=annotation-type-mismatch
  File "/<project venv>/lib/python3.9/site-packages/supersuit/vector/sb3_vector_wrapper.py", line 12, in reset
    return self.venv.reset()
  File "/<project venv>/lib/python3.9/site-packages/supersuit/vector/concat_vec_env.py", line 41, in reset
    return self.concat_obs([vec_env.reset() for vec_env in self.vec_envs])
  File "/<project venv>/lib/python3.9/site-packages/supersuit/vector/concat_vec_env.py", line 41, in <listcomp>
    return self.concat_obs([vec_env.reset() for vec_env in self.vec_envs])
  File "/<project venv>/lib/python3.9/site-packages/supersuit/vector/markov_vector_wrapper.py", line 55, in reset
    return self.concat_obs(self.par_env.reset())
  File "/<project venv>/lib/python3.9/site-packages/supersuit/vector/markov_vector_wrapper.py", line 44, in concat_obs
    self.obs_buffer[i] = obs_dict[agent]
ValueError: could not broadcast input array from shape (84,84,3) into shape (84,84)
```

If I comment out the `frame_stack_v1` it will all work.

From an initial investigation, it seems like the wrapper is applied to `observation_space(agent)` but not `observation_spaces`.

```
(Pdb) p list(env.observation_spaces.values())[0].shape
(84, 84)
(Pdb) p env.observation_space('piston_0').shape
(84, 84, 3)
```

### Current module version:

```
$ pip freeze
absl-py==0.14.1
aioupnp==0.0.18
alembic==1.7.4
altair==4.1.0
attrs==21.2.0
autopage==0.4.0
autoslot==2021.4.2
boltons==21.0.0
cachetools==4.2.4
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.7
cliff==3.9.0
cloudpickle==1.6.0
cmaes==0.8.2
cmd2==2.2.0
colorama==0.4.4
colorlog==6.5.0
cycler==0.10.0
defusedxml==0.7.1
dill==0.3.4
entrypoints==0.3
google-auth==1.35.0
google-auth-oauthlib==0.4.6
greenlet==1.1.2
grpcio==1.41.0
gym==0.18.3
hanabi-learning-environment==0.0.1
idna==3.3
Jinja2==3.0.2
joblib==0.16.0
jsonschema==4.1.0
kiwisolver==1.3.2
Mako==1.1.5
Markdown==3.3.4
MarkupSafe==2.0.1
matplotlib==3.3.4
netifaces==0.11.0
numpy==1.19.5
oauthlib==3.1.1
opencv-python==3.4.15.55
optuna==2.1.0
packaging==21.0
pandas==1.1.5
pbr==5.6.0
PettingZoo==1.12.0
Pillow==8.2.0
prettytable==2.2.1
protobuf==3.18.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pygame==2.0.0
pyglet==1.5.15
pymunk==6.2.0
pyparsing==2.4.7
pyperclip==1.8.2
pyrsistent==0.18.0
python-chess==0.31.4
python-dateutil==2.8.2
pytz==2021.3
PyYAML==6.0
requests==2.26.0
requests-oauthlib==1.3.0
rlcard==1.0.4
rsa==4.7.2
scipy==1.7.1
six==1.15.0
SQLAlchemy==1.4.25
stable-baselines3==1.2.0
stevedore==3.4.0
SuperSuit==3.2.0
tensorboard==2.3.0
tensorboard-plugin-wit==1.8.0
termcolor==1.1.0
toolz==0.11.1
torch==1.9.1
torchvision==0.8.2
tqdm==4.62.3
trueskill==0.4.5
typing-extensions==3.10.0.2
urllib3==1.26.7
wcwidth==0.2.5
Werkzeug==1.0.1
```

Thank you!

**Comment by dat-boris** [comment]
Seems like this recent change https://github.com/Farama-Foundation/SuperSuit/pull/107/files undo the patching of `observation_spaces`.

I tried to revert to the last version of SuperSuit 3.1.0  and got a different error
```
  File "<project-venv>/lib/python3.9/site-packages/supersuit/lambda_wrappers/observation_lambda.py", line 64, in _modify_spaces
    self.observation_spaces = new_spaces
AttributeError: can't set attribute
```

I will try if adding back the `observation_spaces` patching will help.

**Comment by benblack769** [comment]
It looks like this problem will be fixed by https://github.com/Farama-Foundation/SuperSuit/pull/112
