### ISSUE TITLE
ctypes.CDLL ——>cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by JiahengZeng** [Farama-Foundation/PettingZoo#534]
When I try to import a library from Magent, I Encountered the following problems. Since I don't know much about C++ and linux. Can someone help me？

Traceback (most recent call last):
  File "/home/zjh/pycharm_project/test.py", line 1, in <module>
    from pettingzoo.magent import battle_v3
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/home/zjh/pycharm_project/venv/lib/python3.8/site-packages/pettingzoo/magent/__init__.py", line 5, in __getattr__
    return depricated_handler(env_name, __path__, __name__)
  File "/home/zjh/pycharm_project/venv/lib/python3.8/site-packages/pettingzoo/utils/deprecated_module.py", line 27, in depricated_handler
    return importlib.import_module(f"{module_name}.{env_name}")
  File "/home/zjh/anaconda3/envs/tf2/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/zjh/pycharm_project/venv/lib/python3.8/site-packages/pettingzoo/magent/battle_v3.py", line 4, in <module>
    import magent
  File "/home/zjh/pycharm_project/magent/__init__.py", line 2, in <module>
    from . import utility
  File "/home/zjh/pycharm_project/magent/utility.py", line 12, in <module>
    from magent.builtin.rule_model import RandomActor
  File "/home/zjh/pycharm_project/magent/builtin/rule_model/__init__.py", line 2, in <module>
    from .rush import RushPredator
  File "/home/zjh/pycharm_project/magent/builtin/rule_model/rush.py", line 7, in <module>
    from magent.c_lib import _LIB, as_int32_c_array, as_float_c_array
  File "/home/zjh/pycharm_project/magent/c_lib.py", line 42, in <module>
    _LIB = _load_lib()
  File "/home/zjh/pycharm_project/magent/c_lib.py", line 21, in _load_lib
    lib = ctypes.CDLL(path_to_so_file, ctypes.RTLD_GLOBAL)
  File "/home/zjh/anaconda3/envs/tf2/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/zjh/pycharm_project/magent/../../build/libmagent.so: cannot open shared object file: No such file or directory

**Comment by benblack769** [comment]
Hmm. It seems as though something went wrong during installation. I see that it is looking in this pycharm_project folder for the binary. Can you describe:

1. What OS you have
2. What process you went through to install magent

This will be helpful information so that we can track down what is going wrong here.

**Comment by JiahengZeng** [comment]
1.OS: Ubuntu20.04 in dual-system mode.
2.( pycharm_project's venv ( inherit from conda's base))pip install pettingzoo
Must i install the magent specifically？

**Comment by benblack769** [comment]
Ok, I think I understand what is going on. The stack trace is reporting some calls in files which do not exist in our distribution of magent https://github.com/Farama-Foundation/MAgent (particularly magent/builtin/rule_model/rush.py). Have you tried to install Magent before?  Pettingzoo relies on a maintained fork of the MAgent repo. I would try to uninstall magent and then `pip install magent` to install the version of magent which pettingzoo depends on.

Let me know if this works.

**Comment by JiahengZeng** [comment]
Well, I think that it must be the problem you mentioned since I had tried the older item(https://github.com/geek-ai/MAgent).It did work! But its older item can't be install by pip(git clone and bash rather than pip). After downloading it, it still needs some work to connect it to the pettingzoo interface, but I'm not familiar with these work.
The only version that can be downloaded from pip(https://github.com/Farama-Foundation/MAgent) also have the problem that I mentioned. 
I tried to import Magent from pettingzoo since its convenient interactive design.
How I wish I could use magent directly through pettingzoo. T_T
(Or maybe it's not difficult to arrange the older item? If so, please let me know!! thank you ^ ^

**Comment by jkterry1** [comment]
Could you please create a new virtualenv from scratch and then use `pip install pettingzoo[magent]`? I believe that should fix this

**Comment by benblack769** [comment]
Or a new pycharm project.

**Comment by JiahengZeng** [comment]
It does work! Thank you very much!
