### ISSUE TITLE
Error importing Atari environments

### ISSUE THREAD

**Issue by nikhilweee** [Farama-Foundation/PettingZoo#565]
@jkterry1 I believe I'm doing things right, but something is wrong and it needs immediate attention.

Version Information
```bash
$ python --version
Python 3.8.12
$ python -c "import pettingzoo; print(pettingzoo.__version__)"
1.13.1
$ conda --version
conda 4.10.3
```

Try importing the regular way:
```bash
$ python -c "from pettingzoo.atari import pong_v2"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/ext3/miniconda3/envs/base/lib/python3.8/site-packages/pettingzoo/atari/__init__.py", line 5, in __getattr__
    return depricated_handler(env_name, __path__, __name__)
  File "/ext3/miniconda3/envs/base/lib/python3.8/site-packages/pettingzoo/utils/deprecated_module.py", line 42, in depricated_handler
    raise ImportError(f"cannot import name '{env_name}' from '{module_name}'")
ImportError: cannot import name 'pong_v2' from 'pettingzoo.atari'
```

Try the suggestion from https://github.com/Farama-Foundation/PettingZoo/issues/550#issuecomment-979646948:
```bash
$ python -c "import pettingzoo.atari.pong_v2 as pong_v2"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/ext3/miniconda3/envs/base/lib/python3.8/site-packages/pettingzoo/atari/pong_v2.py", line 3, in <module>
    from .base_atari_env import BaseAtariEnv, base_env_wrapper_fn, parallel_wrapper_fn
  File "/ext3/miniconda3/envs/base/lib/python3.8/site-packages/pettingzoo/atari/base_atari_env.py", line 4, in <module>
    import multi_agent_ale_py
ModuleNotFoundError: No module named 'multi_agent_ale_py'
```

**Comment by nikhilweee** [comment]
Nevermind, a quick `pip install pettingzoo[atari]` fixed the issue. Sorry for bothering you!
