### ISSUE TITLE
13 lines tutorial error

### ISSUE THREAD

**Issue by capyun** [Farama-Foundation/PettingZoo#586]
when i run 13 lines tutorial on windows, i get this error:
Traceback (most recent call last):
  File "E:/workspace_pycharm/MADDPG_torch-master/ppo.py", line 28, in <module>
    model.learn(total_timesteps=2000000)
  File "D:\Environ\anaconda3\envs\AI\lib\site-packages\stable_baselines3\ppo\ppo.py", line 299, in learn
    return super(PPO, self).learn(
  File "D:\Environ\anaconda3\envs\AI\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 226, in learn
    total_timesteps, callback = self._setup_learn(
  File "D:\Environ\anaconda3\envs\AI\lib\site-packages\stable_baselines3\common\base_class.py", line 420, in _setup_learn
    self._last_obs = self.env.reset()  # pytype: disable=annotation-type-mismatch
  File "D:\Environ\anaconda3\envs\AI\lib\site-packages\stable_baselines3\common\vec_env\vec_transpose.py", line 98, in reset
    return self.transpose_observations(self.venv.reset())
  File "D:\Environ\anaconda3\envs\AI\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py", line 62, in reset
    self._save_obs(env_idx, obs)
  File "D:\Environ\anaconda3\envs\AI\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py", line 92, in _save_obs
    self.buf_obs[key][env_idx] = obs
ValueError: could not broadcast input array from shape (20,84,84,3) into shape (84,84,3)

thanks.

**Comment by benblack769** [comment]
Could you post all the versions of the libraries you are using (SB3, gym, pettingzoo, supersuit)?

**Comment by jkterry1** [comment]
I'm closing this due to inactivity, please let us know if you need further help
