### ISSUE TITLE
[bug] AttributeError: 'function' object has no attribute 'shape'

### ISSUE THREAD

**Issue by cool-RR** [Farama-Foundation/PettingZoo#716]
[Version info](https://gist.github.com/cool-RR/111b5f6d93a75ffa146f0e42b23d6da9).

I run this code:

```
from stable_baselines3 import PPO
from stable_baselines3.ppo import CnnPolicy

from pettingzoo.classic import chess_v5

env = chess_v5.env()
model = PPO(CnnPolicy, env)
```

I get this traceback:

```
Traceback (most recent call last):
  File "/herring/smoky/buggo.py", line 7, in <module>
    model = PPO(CnnPolicy, env)
  File "/home/ramrachum/.local/lib/python3.9/site-packages/stable_baselines3/ppo/ppo.py", line 96, in __init__
    super(PPO, self).__init__(
  File "/home/ramrachum/.local/lib/python3.9/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 77, in __init__
    super(OnPolicyAlgorithm, self).__init__(
  File "/home/ramrachum/.local/lib/python3.9/site-packages/stable_baselines3/common/base_class.py", line 163, in __init__
    env = self._wrap_env(env, self.verbose, monitor_wrapper)
  File "/home/ramrachum/.local/lib/python3.9/site-packages/stable_baselines3/common/base_class.py", line 207, in _wrap_env
    env = DummyVecEnv([lambda: env])
  File "/home/ramrachum/.local/lib/python3.9/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 29, in __init__
    self.keys, shapes, dtypes = obs_space_info(obs_space)
  File "/home/ramrachum/.local/lib/python3.9/site-packages/stable_baselines3/common/vec_env/util.py", line 74, in obs_space_info
    shapes[key] = box.shape
AttributeError: 'function' object has no attribute 'shape'
```

I investigated a bit. Looking at [this code](https://github.com/DLR-RM/stable-baselines3/blob/ed308a7/stable_baselines3/common/vec_env/dummy_vec_env.py#L28) in Stable Baselines 3, it expects the observation space to be available as `env.observation_space`, while PettingZoo makes it available as `env.observation_space()`.

What should be done here? 

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo (**required**)

**Comment by jjshoots** [comment]
PettingZoo is inherently a multi agent RL library, while Stable Baselines 3 is built for single agent RL (though some hacking can be done with an example [here](https://github.com/Farama-Foundation/PettingZoo/blob/master/tutorials/13_lines.py)). The code that you're using assumes that `chess_v5` is a `gym` env, which it isn't.

What should be done is to actually convert the `chess_v5`'s AEC_Env to a parallel env such that it is usable with Stable Baselines 3 using `turn_based_aec_to_parallel_wrapper` wrapper in `pettingzoo.utils.conversions`. Though it should be noted that you should know what the wrapper is doing first before using it.

**Comment by cool-RR** [comment]
Thanks, this is my mistake. I'll figure it out.
