### ISSUE TITLE
13_lines.py tutorial not working due to " AttributeError: 'ProcConcatVec' object has no attribute 'pipes' "

### ISSUE THREAD

**Issue by tomkouwenhoven** [Farama-Foundation/PettingZoo#812]
I would love some help with the following problem:

**Description**
After installing PettingZoo, Gym, stable-baselines3, and SuperSuit I was not able to run the 13_lines.py example of the pistonball_v6.parallel_env. I have copied the code from commit [24b41bc](https://github.com/Farama-Foundation/PettingZoo/commit/24b41bcb37790a93c761060fd530d9f9115f3021) and received an attribute error on ProcConcatVec which has no attribute 'pipes'.  

**Code example**
As mentioned above, I downloaded the latest 13_lines.py (last updated on Sept 25 2022) file directly from this GitHub and tried to run it in the terminal on a MacBook Air M1 2020.  

**Stack trace:**
```
python 13_lines.py
Traceback (most recent call last):
  File "/Users/tom/Desktop/PhD/Gym/13_lines.py", line 65, in <module>
    main()
  File "/Users/tom/Desktop/PhD/Gym/13_lines.py", line 24, in main
    env = ss.concat_vec_envs_v1(env, 8, num_cpus=4, base_class="stable_baselines3")
  File "/Users/tom/Desktop/PhD/Gym/venv/lib/python3.9/site-packages/supersuit/vector/vector_constructors.py", line 60, in concat_vec_envs_v1
    vec_env = MakeCPUAsyncConstructor(num_cpus)(*vec_env_args(vec_env, num_vec_envs))
  File "/Users/tom/Desktop/PhD/Gym/venv/lib/python3.9/site-packages/supersuit/vector/constructors.py", line 36, in constructor
    return ProcConcatVec(
  File "/Users/tom/Desktop/PhD/Gym/venv/lib/python3.9/site-packages/supersuit/vector/multiproc_vec.py", line 123, in __init__
    raise NotImplementedError("The wrapper ProcConcatVec is temporarily depreciated whilst it is being debugged. "
NotImplementedError: The wrapper ProcConcatVec is temporarily depreciated whilst it is being debugged. Please refer to https://github.com/Farama-Foundation/SuperSuit/pull/165 for more information, or to contact the devs in regard to this.
Exception ignored in: <function ProcConcatVec.__del__ at 0x128343790>
Traceback (most recent call last):
  File "/Users/tom/Desktop/PhD/Gym/venv/lib/python3.9/site-packages/supersuit/vector/multiproc_vec.py", line 225, in __del__
    for pipe in self.pipes:
AttributeError: 'ProcConcatVec' object has no attribute 'pipes'
```

**System Info**
Packages installed on a clean virtual environment using Python 3.9.7:
Gym, Version: 0.26.2, installed through pip
PettingZoo, Version: 1.21.0, installed through pip
SuperSuit, Version: 3.6.0, installed through pip

Operating system: MacBook Air (M1, 2020), Monterey version 12.4

I would greatly appreciate your help.

**Comment by tomkouwenhoven** [comment]
Thanks a lot, I am looking forward to the moment when the tutorials are revamped :-)
