### ISSUE TITLE
Using Stable_baselines3 observation and action spaces with pettingzoo

### ISSUE THREAD

**Issue by YigitSari** [Farama-Foundation/PettingZoo#861]
### Question

I am trying to use StableBaselines3's PPO in simple_spread_v2 from PettingZoo.I have used the environment wrapper but it doesn't accept action and observation spaces from the wrapped environment.Here is the Code I got from various tutorials: 
```
from stable_baselines3 import PPO
from pettingzoo.mpe import simple_spread_v2
import supersuit as ss

env = simple_spread_v2.parallel_env()
env = ss.pettingzoo_env_to_vec_env_v1(env)
env = ss.concat_vec_envs_v1(env, 1, 1, base_class='stable_baselines3')
model = PPO('MlpPolicy', env)
model.learn(total_timesteps=10000)
```

And when I run the code I got: 

```
Traceback (most recent call last):
  File "/home/yigit/BA/phoenix-drone-simulation/particle/MARL/test4.py", line 8, in <module>
    model = PPO('MlpPolicy', env)
  File "/home/yigit/BA/venv/lib/python3.10/site-packages/stable_baselines3/ppo/ppo.py", line 107, in __init__
    super().__init__(
  File "/home/yigit/BA/venv/lib/python3.10/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 81, in __init__
    super().__init__(
  File "/home/yigit/BA/venv/lib/python3.10/site-packages/stable_baselines3/common/base_class.py", line 187, in __init__
    assert isinstance(self.action_space, supported_action_spaces), (
AssertionError: The algorithm only supports (<class 'gym.spaces.box.Box'>, <class 'gym.spaces.discrete.Discrete'>, <class 'gym.spaces.multi_discrete.MultiDiscrete'>, <class 'gym.spaces.multi_binary.MultiBinary'>) as action spaces but Discrete(5) was provided
```

I can't understand the fact that I am sending Discrete(5) which is a member of <class 'gym.spaces.discrete.Discrete'> but StableBaselines refuses to accept it.Am I doing something wrong ?

**Comment by cibeah** [comment]
Hello, 

I encountered a similar problem. This is seemingly because PettingZoo now uses the `gymnasium`  package, a fork of Gym maintained by Farama, whereas stable-baselines3 still uses the legacy OpenAI's gym. Validity test for environments in sb3 requires them to be an instance of gym environments. 
I managed to work around this by replacing gymnasium by gym in my custom PettingZoo environments (the reverse can also be done but is usually much more work), but this was just a quick fix. I'm not sure how this can be resolved, it will probably mean requesting stable-baselines3 to switch to gymnasium.

**Comment by WillDudley** [comment]
> Hello, 
> 
> I encountered a similar problem. This is seemingly because PettingZoo now uses the `gymnasium`  package, a fork of Gym maintained by Farama, whereas stable-baselines3 still uses the legacy OpenAI's gym. Validity test for environments in sb3 requires them to be an instance of gym environments. 
> I managed to work around this by replacing gymnasium by gym in my custom PettingZoo environments (the reverse can also be done but is usually much more work), but this was just a quick fix. I'm not sure how this can be resolved, it will probably mean requesting stable-baselines3 to switch to gymnasium.

Yes, we are working with sb3 to make it compatible with Gymnasium at https://github.com/DLR-RM/stable-baselines3/pull/780

Until then, unfortunately you'd have to use older versions of the libraries, or use alternative learning libraries such as CleanRL or Tianshou.

**Comment by hermanmostein** [comment]
> Hello,
> 
> I encountered a similar problem. This is seemingly because PettingZoo now uses the `gymnasium` package, a fork of Gym maintained by Farama, whereas stable-baselines3 still uses the legacy OpenAI's gym. Validity test for environments in sb3 requires them to be an instance of gym environments. I managed to work around this by replacing gymnasium by gym in my custom PettingZoo environments (the reverse can also be done but is usually much more work), but this was just a quick fix. I'm not sure how this can be resolved, it will probably mean requesting stable-baselines3 to switch to gymnasium.

Did you get it running at all? I am having the same issues, but I cannot get anything running.

**Comment by elliottower** [comment]
This should be possible now that SB3 supports Gymnasium, we are working on an SB3 tutorial, will link it here when it is finished.
